services:
  - type: web
    name: impulso-capital-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: CORS_ORIGIN
        value: https://tu-frontend-netlify.netlify.app
      - key: GCS_BUCKET
        value: proyecto-alcaldia-2025
      - key: GCP_PROJECT_ID
        value: proyecto-alcaldia-461421
      - key: EMAIL_USER
        value: tecnologia@propais.org.co
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://tu-frontend-netlify.netlify.app
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: ./gcs-credentials.json 