services:
  - type: web
    name: impulso-capital-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: CORS_ORIGIN
        value: https://emprendopolis.netlify.app
      - key: GCS_BUCKET
        value: emprendopolis-files-2025
      - key: GCP_PROJECT_ID
        value: emprendopolis-storage
      - key: EMAIL_USER
        value: tecnologia@propais.org.co
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://emprendopolis.netlify.app
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /opt/render/project/src/impulso-capital_back/gcs-credentials.json
    secretFiles:
      - key: gcs-credentials
        name: gcs-credentials.json 